#!/bin/bash

if [ $# -lt 1 ]
then
        read -p "please input commit message:" desc
else
	echo "comment message = $1"
	desc="$1"
fi

git pull origin master
JEKYLL_ENV=production bundle exec jekyll b
git add . && \
git add -u && \
git commit -m "$desc" && \
git push -u "origin" master

cd _site && sh pushit "build-new-flyca"